version: "3.9"

services:
  # notebooks:
  #   build:
  #     context: ./notebooks
  #     dockerfile: Dockerfile
  #   command: >
  #     sh -c "jupyter notebook --allow-root --no-browser --port=8888 --ip 0.0.0.0 --NotebookApp.token='' --NotebookApp.password=''"
  #   env_file:
  #     - .env
  #   ports:
  #     - "8888:8888"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./notebooks:/container
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations app &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:4595"
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-4595}:4595"
    volumes:
      - ./backend/app/migrations:/container/app/migrations
    depends_on:
      - db
  db:
    image: postgis/postgis:12-3.3
    restart: always
    env_file:
      - .env
    ports:
      - "${SQL_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${SQL_USER:-user}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-password}
      POSTGRES_DB: ${SQL_DATABASE:-postgres}
      # for connecting outside the local docker-compose network namespace
      # update /var/lib/postgresql/data/pg_hba.conf adding a line: 
      # host all all {BACKEND_HOST} trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
