version: "3.9"

services:
  # notebooks:
  #   build:
  #     context: ./notebooks
  #     dockerfile: Dockerfile
  #   command: >
  #     sh -c "jupyter notebook"
  #   env_file:
  #     - .env
  #   ports:
  #     - "8888:8888"
  #   depends_on:
  #     - db
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:4595"
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT:-4595}:4595"
    depends_on:
      - db
  db:
    image: postgres:12.15-alpine
    restart: always
    env_file:
      - .env
    ports:
      - "${SQL_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${SQL_USER:-user}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-password}
      POSTGRES_DB: ${SQL_DATABASE:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
