# Generated by Django 4.1.5 on 2023-07-31 03:30

import app.data_models.apistructure
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AmazonMetadataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asin", models.CharField(db_index=True, max_length=255, unique=True)),
                ("also_buy", models.JSONField()),
                ("also_view", models.JSONField()),
                ("brand", models.CharField(max_length=255)),
                ("category", models.JSONField()),
                (
                    "date",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("details", models.TextField(blank=True, null=True)),
                ("feature", models.JSONField()),
                ("image", models.JSONField()),
                ("main_cat", models.CharField(max_length=255)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("rank", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
            ],
            bases=(app.data_models.apistructure.APIModelStructure, models.Model),
        ),
        migrations.CreateModel(
            name="AmazonReviewModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asin", models.CharField(db_index=True, max_length=255)),
                ("overall", models.FloatField()),
                ("reviewText", models.TextField(blank=True)),
                ("reviewerID", models.CharField(max_length=255, unique=True)),
                ("reviewerName", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True)),
                ("unixReviewTime", models.PositiveBigIntegerField()),
                ("verified", models.BooleanField(default=False)),
                ("style", models.JSONField(blank=True, null=True)),
                ("vote", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("image", models.JSONField(blank=True, null=True)),
            ],
            bases=(app.data_models.apistructure.APIModelStructure, models.Model),
        ),
    ]
