# Generated by Django 4.1.5 on 2023-07-31 03:35

import app.data_models.apistructure
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewEmotionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=255)),
                ('overall', models.FloatField()),
                ('anger', models.FloatField()),
                ('disgust', models.FloatField()),
                ('fear', models.FloatField()),
                ('joy', models.FloatField()),
                ('neutral', models.FloatField()),
                ('sadness', models.FloatField()),
                ('surprise', models.FloatField()),
            ],
            bases=(app.data_models.apistructure.APIModelStructure, models.Model),
        ),
    ]
