# Generated by Django 4.1.5 on 2023-08-02 01:45

import app.data_models.apistructure
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCAEncodedReviewEmotionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=255)),
                ('reviewerID', models.CharField(db_index=True, max_length=255)),
                ('vec_d1', models.FloatField()),
                ('vec_d2', models.FloatField()),
                ('vec_d3', models.FloatField()),
                ('vec_d4', models.FloatField()),
            ],
            bases=(app.data_models.apistructure.APIModelStructure, models.Model),
        ),
        migrations.CreateModel(
            name='ReviewEmotionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(db_index=True, max_length=255)),
                ('reviewerID', models.CharField(db_index=True, max_length=255)),
                ('overall', models.FloatField()),
                ('anger', models.FloatField()),
                ('disgust', models.FloatField()),
                ('fear', models.FloatField()),
                ('joy', models.FloatField()),
                ('neutral', models.FloatField()),
                ('sadness', models.FloatField()),
                ('surprise', models.FloatField()),
            ],
            bases=(app.data_models.apistructure.APIModelStructure, models.Model),
        ),
        migrations.AlterField(
            model_name='amazonreviewmodel',
            name='reviewerID',
            field=models.CharField(max_length=255),
        ),
    ]
