# Generated by Django 4.1.5 on 2023-08-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pcaencodedreviewemotionsmodel_reviewemotionsmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonreviewmodel',
            name='overall',
            field=models.FloatField(null=True),
        ),
    ]
