# Generated by Django 4.1.5 on 2023-08-02 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_pcaencodedreviewemotionsmodel_reviewemotionsmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amazonreviewmodel",
            name="reviewText",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="amazonreviewmodel",
            name="summary",
            field=models.TextField(blank=True, default=""),
        ),
    ]
