# Generated by Django 4.1.5 on 2023-08-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_amazonreviewmodel_reviewtext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonreviewmodel',
            name='overall',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
