# Generated by Django 4.1.5 on 2023-08-03 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_amazonreviewmodel_overall'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='amazonreviewmodel',
            unique_together={('asin', 'reviewerID')},
        ),
        migrations.AlterUniqueTogether(
            name='pcaencodedreviewemotionsmodel',
            unique_together={('asin', 'reviewerID')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewemotionsmodel',
            unique_together={('asin', 'reviewerID')},
        ),
    ]
