# Generated by Django 4.1.5 on 2023-08-04 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_amazonreviewmodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amazonmetadatamodel',
            name='main_cat',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
